"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { FormEvent, Suspense, useEffect, useState } from "react";
import { ApiError, apiRequest } from "@/lib/api";
type Seat={id:string;row_label:string;seat_number:string;seat_type:string;price_amount:string;currency:string;status:string}; type Hold={id:string;expires_at:string;seat_ids:string[]};
export default function CheckoutPage(){return <Suspense fallback={<p aria-busy="true">Memuat checkout…</p>}><Checkout /></Suspense>;}
function Checkout(){const showtimeID=useSearchParams().get("showtimeId")??"";const[seats,setSeats]=useState<Seat[]>([]);const[selected,setSelected]=useState<string[]>([]);const[loading,setLoading]=useState(Boolean(showtimeID));const[submitting,setSubmitting]=useState(false);const[error,setError]=useState("");const[hold,setHold]=useState<Hold|null>(null);
 const load=()=>{if(!showtimeID){setLoading(false);return;}setLoading(true);apiRequest<{seats:Seat[]}>(`/showtimes/${showtimeID}/seats`).then(r=>setSeats(r.seats)).catch((e:unknown)=>setError(e instanceof ApiError?e.message:"Peta kursi tidak dapat dimuat.")).finally(()=>setLoading(false));};useEffect(load,[showtimeID]); const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!showtimeID||selected.length===0)return;setSubmitting(true);setError("");try{const order=await apiRequest<Hold>("/orders",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({showtime_id:showtimeID,seat_ids:selected})});await apiRequest(`/orders/${order.id}/payment-intents`,{method:"POST"});setHold(order);}catch(e){setError(e instanceof ApiError?e.message:"Pesanan tidak dapat dibuat.");}finally{setSubmitting(false);}};
 if(!showtimeID)return <section><h1>Pilih kursi</h1><p className="notice">Pilih jadwal terlebih dahulu dari halaman jadwal.</p></section>;if(hold)return <section className="stack"><h1>Hold kursi dibuat</h1><p className="notice">Selesaikan pembayaran sebelum <time dateTime={hold.expires_at}>{new Date(hold.expires_at).toLocaleString("id-ID")}</time>. Status pembayaran hanya berubah setelah webhook provider terverifikasi.</p><Link className="button" href={`/orders/${hold.id}`}>Lihat status pesanan</Link></section>;
 return <section className="stack" aria-labelledby="checkout-title"><div><h1 id="checkout-title">Pilih kursi</h1><p className="muted">Kursi yang di-hold pelanggan lain tidak dapat dipilih.</p></div>{error&&<p className="error" role="alert">{error}</p>}{loading?<p aria-busy="true">Memuat peta kursi…</p>:seats.length===0?<p className="notice">Tidak ada kursi yang dapat dipesan.</p>:<form className="stack" onSubmit={submit}><fieldset><legend>Peta kursi</legend><div className="seat-map">{seats.map(s=><button type="button" className="seat" data-selected={selected.includes(s.id)} key={s.id} disabled={s.status!=="AVAILABLE"} aria-pressed={selected.includes(s.id)} onClick={()=>toggle(s.id)}>{s.row_label}{s.seat_number} · {s.seat_type}<br/><small>{s.status}</small></button>)}</div></fieldset><p>{selected.length} kursi dipilih</p><button disabled={submitting||selected.length===0}>{submitting?"Membuat hold…":"Lanjut ke pembayaran"}</button></form>}</section>;}
