"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { FormEvent, Suspense, useEffect, useState } from "react";
import { ApiError, apiRequest } from "@/lib/api";
type Showtime = { id:string; cinema_name:string; cinema_city:string; studio_name:string; starts_at:string; ends_at:string; base_price:string; currency:string };
const today = new Date().toISOString().slice(0, 10);
export default function ShowtimesPage() { return <Suspense fallback={<p aria-busy="true">Memuat jadwal…</p>}><Showtimes /></Suspense>; }
function Showtimes() { const query = useSearchParams(); const [movieID, setMovieID] = useState(query.get("movieId") ?? ""); const [date, setDate] = useState(today); const [showtimes, setShowtimes] = useState<Showtime[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 const load=(event?:FormEvent)=>{event?.preventDefault(); if(!movieID){setError("Masukkan ID film dari katalog terlebih dahulu.");return;} setLoading(true);setError("");apiRequest<{showtimes:Showtime[]}>(`/movies/${movieID}/showtimes?date=${date}`).then((r)=>setShowtimes(r.showtimes)).catch((e:unknown)=>setError(e instanceof ApiError?e.message:"Jadwal tidak dapat dimuat.")).finally(()=>setLoading(false));}; useEffect(()=>{if(query.get("movieId"))load();},[]);
 return <section className="stack" aria-labelledby="showtimes-title"><div><h1 id="showtimes-title">Jadwal pertunjukan</h1><p className="muted">Tanggal menggunakan zona waktu UTC dari API.</p></div><form className="form-grid" onSubmit={load}><label>ID film<input value={movieID} onChange={(e)=>setMovieID(e.target.value)} required /></label><label>Tanggal<input type="date" value={date} onChange={(e)=>setDate(e.target.value)} required /></label><button>Temukan jadwal</button></form>{error&&<p className="error" role="alert">{error}</p>}{loading?<p aria-busy="true">Memuat jadwal…</p>:showtimes.length>0?<div className="grid">{showtimes.map((s)=><article className="card" key={s.id}><h2>{s.cinema_name}</h2><p>{s.studio_name} · {s.cinema_city}</p><p><time dateTime={s.starts_at}>{new Date(s.starts_at).toLocaleString("id-ID")}</time></p><p>{s.currency} {s.base_price}</p><Link className="button" href={`/checkout?showtimeId=${s.id}`}>Pilih kursi</Link></article>)}</div>:!loading&&!error?<p className="notice">Pilih film dan tanggal untuk melihat jadwal.</p>:null}</section>; }
