"use client";
import { FormEvent, useEffect, useState } from "react";
import { ApiError, apiRequest } from "@/lib/api";

export type Field = { name: string; label: string; type?: "text" | "number" | "date-time" | "textarea"; optional?: boolean };
type RecordValue = Record<string, unknown> & { id: string };
export function CrudWorkstation({ title, endpoint, responseKey, fields }: { title: string; endpoint: string; responseKey: string; fields: Field[] }) {
  const [records, setRecords] = useState<RecordValue[]>([]); const [editing, setEditing] = useState<RecordValue | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = () => { setLoading(true); setError(""); apiRequest<Record<string, RecordValue[]>>(endpoint).then((result) => setRecords(result[responseKey] ?? [])).catch((e: unknown) => setError(e instanceof ApiError ? e.message : "Data tidak dapat dimuat.")).finally(() => setLoading(false)); };
  useEffect(load, [endpoint, responseKey]);
  const reset = () => { setEditing(null); setMessage(""); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(""); setMessage(""); const form = new FormData(event.currentTarget); const data: Record<string, unknown> = {}; for (const field of fields) { const raw = String(form.get(field.name) ?? "").trim(); if (field.optional && !raw) continue; data[field.name] = field.type === "number" ? Number(raw) : field.type === "date-time" ? new Date(raw).toISOString() : raw; } try { await apiRequest(editing ? `${endpoint}/${editing.id}` : endpoint, { method: editing ? "PATCH" : "POST", body: JSON.stringify(data) }); setMessage(editing ? "Perubahan disimpan." : "Data dibuat."); reset(); load(); } catch (e) { setError(e instanceof ApiError ? e.message : "Perubahan tidak dapat disimpan."); } finally { setBusy(false); } };
  const remove = async (record: RecordValue) => { setBusy(true); setError(""); try { await apiRequest(`${endpoint}/${record.id}`, { method: "DELETE" }); setMessage("Data dihapus."); if (editing?.id === record.id) reset(); load(); } catch (e) { setError(e instanceof ApiError ? e.message : "Data tidak dapat dihapus."); } finally { setBusy(false); } };
  return <section className="stack" aria-labelledby={`${responseKey}-title`}><div><h1 id={`${responseKey}-title`}>{title}</h1><p className="muted">Pilih Ubah untuk mengganti seluruh data, atau hapus jika belum memiliki dependensi.</p></div><form className="form-grid" onSubmit={submit}><h2>{editing ? "Ubah data" : "Tambah data"}</h2>{fields.map((field) => <label key={field.name}>{field.label}{field.type === "textarea" ? <textarea name={field.name} defaultValue={String(editing?.[field.name] ?? "")} required={!field.optional} /> : <input name={field.name} type={field.type === "date-time" ? "datetime-local" : field.type ?? "text"} defaultValue={formatValue(editing?.[field.name], field.type)} required={!field.optional} />}</label>)}<div className="inline"><button disabled={busy}>{busy ? "Menyimpan…" : editing ? "Simpan perubahan" : "Tambah"}</button>{editing && <button className="secondary" type="button" onClick={reset}>Batal</button>}</div></form>{error && <p className="error" role="alert">{error}</p>}{message && <p className="notice" role="status">{message}</p>}{loading ? <p aria-busy="true">Memuat data…</p> : records.length === 0 ? <p className="notice">Belum ada data.</p> : <div className="grid">{records.map((record) => <article className="card" key={record.id}><h2>{String(record.name ?? record.title ?? record.id)}</h2><dl>{fields.map((field) => <><dt key={`${record.id}-${field.name}-label`}>{field.label}</dt><dd key={`${record.id}-${field.name}`}>{String(record[field.name] ?? "—")}</dd></>)}</dl><div className="record-actions"><button className="secondary" onClick={() => { setEditing(record); setMessage(""); }}>Ubah</button><button className="danger" onClick={() => remove(record)} disabled={busy}>Hapus</button></div></article>)}</div>}</section>;
}
function formatValue(value: unknown, type: Field["type"]) { if (value === undefined || value === null) return ""; if (type === "date-time") return new Date(String(value)).toISOString().slice(0, 16); return String(value); }
